### ISSUE TITLE
Output Error: CRITICAL - No media file found!

### ISSUE THREAD

**Issue by sirius-sama** [SamK/ziknfobuiler#1]
This is the first time I have been using this script. And when I pass a folder of music or a music file to the script, the output is: ``CRITICAL - No media file found!``
All dependencies are installed. I checked the files are valid, I tried to pass flac, and mp3 files, but no luck. Still the same issue.

Can you please work on this script again? I saw this script hasn't been updated in the last 8 years.

Terminal logs:
```
$ ./ziknfobuiler "Artist - Album Name (2023) [MP3-320]"/ --template=templates/simple.jinja2 --verbose
CRITICAL - No media file found!
```
```
$ ./ziknfobuiler "Artist - Album Name (2023) [MP3-320]"/
CRITICAL - No media file found!
```

Extra Info:
Python Version - 2.7.18

**Comment by SamK** [comment]
Hi, thanks for the feedback. I didn't know this script was still used. Can you please execute the script with the `-vv` option to enable the debug mode and paste the result here?

**Comment by sirius-sama** [comment]
Hey, thanks for the reply. Here's the log:

```
$ ./ziknfobuiler "Artist - Album Name (2023) [MP3-320]"/ --template=templates/simple.jinja2 -vv
DEBUG - Enabling debug mode.
CRITICAL - No media file found!
```

This script is excellent. Even tho I haven't succeeded in running it. Templating is looks perfect, exactly what I want.
Please try to fix it and it would be great if you convert this script from Python 2.xx to Python 3.xx

**Comment by SamK** [comment]
I can reproduce the issue. I will fix it tomorrow. Thanks!

**Comment by SamK** [comment]
I think i fixed the issue.

However the command line changed: the `--template` param is not necessary anymore.

Le me know what you think.

**Comment by sirius-sama** [comment]
Thanks a lot, it's working like a charm. 
It would be very good if you could move this script to python3.xx.

**Comment by SamK** [comment]
I'll see what I can do. Enjoy.
